const myData = {
  login: "josiahcameron",
  id: 104843561,
  node_id: "U_kgDOBj_JKQ",
  avatar_url: "https://avatars.githubusercontent.com/u/104843561?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/josiahcameron",
  html_url: "https://github.com/josiahcameron",
  followers_url: "https://api.github.com/users/josiahcameron/followers",
  following_url:
    "https://api.github.com/users/josiahcameron/following{/other_user}",
  gists_url: "https://api.github.com/users/josiahcameron/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/josiahcameron/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/josiahcameron/subscriptions",
  organizations_url: "https://api.github.com/users/josiahcameron/orgs",
  repos_url: "https://api.github.com/users/josiahcameron/repos",
  events_url: "https://api.github.com/users/josiahcameron/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/josiahcameron/received_events",
  type: "User",
  site_admin: false,
  name: "Josiah Cameron",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2022-05-03T13:58:14Z",
  updated_at: "2023-01-26T12:58:03Z",
};
